#!/usr/bin/env python3
"""Generate tool-specific adapters from the canonical commands in kav/commands/.

Reads  kav/commands/kav-*.md  (YAML frontmatter: name, description, argument-hint)
Writes
  .claude/skills/kav-<name>/SKILL.md          Claude Code skill, full canonical body inline
  adapters/codex/prompts/kav-<name>.md        Codex CLI custom prompt (~/.codex/prompts/), invoked /prompts:kav-<name>
  adapters/codex/skills/kav-<name>/SKILL.md   Codex skill (copy to .agents/skills/ or ~/.agents/skills/), invoked $kav-<name>

Run from anywhere:  python3 scripts/sync_adapters.py [--check]
--check exits 1 if any adapter is out of date, without writing.
"""
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMANDS = ROOT / "kav" / "commands"
CLAUDE_SKILLS = ROOT / ".claude" / "skills"
CODEX_PROMPTS = ROOT / "adapters" / "codex" / "prompts"
CODEX_SKILLS = ROOT / "adapters" / "codex" / "skills"

GENERATED = "<!-- Generated by scripts/sync_adapters.py from kav/commands/{file}. Edit the canonical file, then re-run. -->"


def parse(path: Path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        sys.exit(f"{path}: missing YAML frontmatter")
    meta = {}
    for line in m.group(1).splitlines():
        if not line.strip():
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        meta[key.strip()] = value
    for required in ("name", "description"):
        if not meta.get(required):
            sys.exit(f"{path}: frontmatter needs '{required}'")
    if meta["name"] != path.stem:
        sys.exit(f"{path}: name '{meta['name']}' must match the filename")
    return meta, m.group(2).lstrip("\n")


def q(value: str) -> str:
    """YAML-safe double-quoted scalar (JSON strings are valid YAML)."""
    return json.dumps(value, ensure_ascii=False)


def claude_skill(meta, body, file):
    fm = [f"name: {meta['name']}", f"description: {q(meta['description'])}"]
    if meta.get("argument-hint"):
        fm.append(f"argument-hint: {q(meta['argument-hint'])}")
    return "---\n" + "\n".join(fm) + "\n---\n\n" + GENERATED.format(file=file) + "\n\n" + body


def codex_prompt(meta, body, file):
    # Codex expands $1..$9, $NAME and $ARGUMENTS inside prompt bodies, so the prompt stays a
    # short pointer to the canonical file instead of inlining text that may contain '$'.
    fm = [f"description: {q(meta['description'])}"]
    if meta.get("argument-hint"):
        fm.append(f"argument-hint: {q(meta['argument-hint'])}")
    return (
        "---\n" + "\n".join(fm) + "\n---\n\n"
        + GENERATED.format(file=file) + "\n\n"
        + f"You are running the Kav command `{meta['name']}`.\n\n"
        + "1. Make sure the current working directory is the Kav repo (it contains `AGENTS.md` and "
        + "`kav/commands/`). If it isn't, ask the author where Kav is cloned and work from there.\n"
        + f"2. Read `kav/commands/{file}` in full and follow it exactly.\n"
        + "3. Also respect the hard rules in `AGENTS.md`.\n\n"
        + "Arguments from the author: $ARGUMENTS\n"
    )


def codex_skill(meta, body, file):
    fm = [f"name: {meta['name']}", f"description: {q(meta['description'])}"]
    return "---\n" + "\n".join(fm) + "\n---\n\n" + GENERATED.format(file=file) + "\n\n" + body


def main():
    check = "--check" in sys.argv
    commands = sorted(COMMANDS.glob("kav-*.md"))
    if not commands:
        sys.exit(f"no commands found in {COMMANDS}")

    outputs = {}
    for path in commands:
        meta, body = parse(path)
        name = meta["name"]
        outputs[CLAUDE_SKILLS / name / "SKILL.md"] = claude_skill(meta, body, path.name)
        outputs[CODEX_PROMPTS / f"{name}.md"] = codex_prompt(meta, body, path.name)
        outputs[CODEX_SKILLS / name / "SKILL.md"] = codex_skill(meta, body, path.name)

    names = {p.stem for p in commands}
    stale = []
    # Remove adapters for commands that no longer exist.
    for base in (CLAUDE_SKILLS, CODEX_SKILLS):
        if base.exists():
            for d in base.glob("kav-*"):
                if d.is_dir() and d.name not in names:
                    stale.append(d)
    if CODEX_PROMPTS.exists():
        for f in CODEX_PROMPTS.glob("kav-*.md"):
            if f.stem not in names:
                stale.append(f)

    changed = [p for p, text in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != text]

    if check:
        for p in changed + stale:
            print(f"out of date: {p.relative_to(ROOT)}")
        sys.exit(1 if changed or stale else 0)

    for p in changed:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(outputs[p], encoding="utf-8")
    for p in stale:
        shutil.rmtree(p) if p.is_dir() else p.unlink()

    print(f"{len(commands)} commands -> {len(outputs)} adapter files "
          f"({len(changed)} written, {len(stale)} removed)")
    for path in commands:
        print(f"  {path.stem}")


if __name__ == "__main__":
    main()


# Keep the committed Codex skills in .agents/skills in step with adapters/codex/skills.
AGENTS_SKILLS = True
if __name__ == "__main__" and AGENTS_SKILLS:
    import shutil
    root = Path(__file__).resolve().parents[1]
    dst = root / ".agents" / "skills"
    shutil.rmtree(dst, ignore_errors=True)
    shutil.copytree(root / "adapters" / "codex" / "skills", dst)
